name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
          cache-dependency-path: next-frontend/package-lock.json

      - name: Install frontend deps
        working-directory: next-frontend
        run: npm ci

      - name: Lint
        working-directory: next-frontend
        run: npx eslint .

      - name: Build
        env:
          NEXT_PUBLIC_API_BASE: ${{ secrets.NEXT_PUBLIC_API_BASE }}
        working-directory: next-frontend
        run: npm run build

